export const FETCH_USER_MEASUREMENTS_START = "FETCH_USER_MEASUREMENTS_START";
export const FETCH_USER_MEASUREMENTS_SUCCESS =
  "FETCH_USER_MEASUREMENTS_SUCCESS";
export const FETCH_USER_MEASUREMENTS_ERROR = "FETCH_USER_MEASUREMENTS_ERROR";

export const CREATE_OR_UPDATE_USER_MEASUREMENTS_START =
  "CREATE_OR_UPDATE_USER_MEASUREMENTS_START";
export const CREATE_OR_UPDATE_USER_MEASUREMENTS_SUCCESS =
  "CREATE_OR_UPDATE_USER_MEASUREMENTS_SUCCESS";
export const CREATE_OR_UPDATE_USER_MEASUREMENTS_ERROR =
  "CREATE_OR_UPDATE_USER_MEASUREMENTS_ERROR";

export const HANDLE_SELECTED_DATE = "HANDLE_SELECTED_DATE";
export const HANDLE_DATE_MATCH = "HANDLE_DATE_MATCH";
