import { CreateUserIngredientInterface } from './interfaces'

export const exampleIngredients : Partial<CreateUserIngredientInterface>[] = [
  {
    name:       'Oat flakes',
    sourceType: 'carbohydrates',
    countType:  '100g',
    kcal:       373,
    carbs:      68,
    protein:    13,
    fat:        6.9,
    price:      0.23,
  },
  {
    name:       'Chicken breast',
    sourceType: 'proteins',
    countType:  '100g',
    kcal:       121,
    carbs:      0,
    protein:    21.8,
    fat:        3.7,
    price:      1.7,
  },
  {
    name:       'Milk - 1,5%',
    sourceType: 'drinks',
    countType:  '100g',
    kcal:       44,
    carbs:      4.7,
    protein:    3,
    fat:        1.5,
    price:      0.22,
  },
  {
    name:       'Banana',
    sourceType: 'fruits',
    countType:  '1 piece',
    kcal:       90,
    carbs:      21,
    protein:    1,
    fat:        0,
    price:      0.8,
  },
  {
    name:       'Linseed',
    sourceType: 'proteins and fats',
    countType:  '100g',
    kcal:       552,
    carbs:      2.3,
    protein:    21,
    fat:        43,
    price:      0.8,
  },
  {
    name:       'Whey Protein SFC',
    sourceType: 'proteins',
    countType:  '100g',
    kcal:       403,
    carbs:      15.7,
    protein:    70,
    fat:        6.6,
    price:      1.9,
  },
  {
    name:       'egg - M',
    sourceType: 'proteins and fats',
    countType:  '1 piece',
    kcal:       73,
    carbs:      0.3,
    protein:    6.5,
    fat:        5,
    price:      0.6,
  },
  {
    name:       'olive',
    sourceType: 'fats',
    countType:  '100g',
    kcal:       823,
    carbs:      0,
    protein:    0,
    fat:        91.4,
    price:      2.5,
  },
  {
    name:       'butter',
    sourceType: 'fats',
    countType:  '100g',
    kcal:       746,
    carbs:      1,
    protein:    1,
    fat:        82,
    price:      3,
  },
  {
    name:       'white rice',
    sourceType: 'carbohydrates',
    countType:  '100g',
    kcal:       341,
    carbs:      76.8,
    protein:    7.4,
    fat:        0,
    price:      0.7,
  },

  {
    name:       'brown rice',
    sourceType: 'carbohydrates',
    countType:  '100g',
    kcal:       353,
    carbs:      76.8,
    protein:    7.1,
    fat:        1.9,
    price:      1.2,
  },

]
