export const FETCH_MEAL_TYPES_START = "FETCH_MEAL_TYPES_START";
export const FETCH_MEAL_TYPES_ERROR = "FETCH_MEAL_TYPES_ERROR";
export const FETCH_MEAL_TYPES_SUCCESS = "FETCH_MEAL_TYPES_SUCCESS";

export const FETCH_USER_MEALS_START = "FETCH_USER_MEALS_START";
export const FETCH_USER_MEALS_SUCCESS = "FETCH_USER_MEALS_SUCCESS";
export const FETCH_USER_MEALS_ERROR = "FETCH_USER_MEALS_ERROR";

export const CREATE_USER_MEAL_START = "CREATE_USER_MEAL_START";
export const CREATE_USER_MEAL_SUCCESS = "CREATE_USER_MEAL_SUCCESS";
export const CREATE_USER_MEAL_ERROR = "CREATE_USER_MEAL_ERROR";

export const DELETE_USER_MEAL_START = "DELETE_USER_MEAL_START";
export const DELETE_USER_MEAL_SUCCESS = "DELETE_USER_MEAL_SUCCESS";
export const DELETE_USER_MEAL_ERROR = "DELETE_USER_MEAL_ERROR";

export const ADD_INGREDIENT_TO_TABLE = "ADD_INGREDIENT_TO_TABLE";
export const REMOVE_INGREDIENT_FROM_TABLE = "REMOVE_INGREDIENT_FROM_TABLE";
export const HANDLE_INGREDIENT_IN_TABLE_MULTIPLIER =
  "HANDLE_INGREDIENT_IN_TABLE_MULTIPLIER";
