export const FETCH_USER_FOOD_DAYS_START = "FETCH_USER_FOOD_DAYS_START";
export const FETCH_USER_FOOD_DAYS_SUCCESS = "FETCH_USER_FOOD_DAYS_SUCCESS";
export const FETCH_USER_FOOD_DAYS_ERROR = "FETCH_USER_FOOD_DAYS_ERROR";

export const CREATE_USER_FOOD_DAYS_START = "CREATE_USER_FOOD_DAYS_START";
export const CREATE_USER_FOOD_DAYS_SUCCESS = "CREATE_USER_FOOD_DAYS_SUCCESS";
export const CREATE_USER_FOOD_DAYS_ERROR = "CREATE_USER_FOOD_DAYS_ERROR";

export const ADD_MEAL_TO_NEW_FOOD_DAY = "ADD_MEAL_TO_NEW_FOOD_DAY";
export const REMOVE_MEAL_FROM_NEW_FOOD_DAY = "REMOVE_MEAL_FROM_NEW_FOOD_DAY";
export const ADD_INGREDIENT_TO_NEW_FOOD_DAY_MEAL =
  "ADD_INGREDIENT_TO_NEW_FOOD_DAY_MEAL";
export const REMOVE_INREDIENT_TO_NEW_FOOD_DAY_MEAL =
  "REMOVE_INREDIENT_TO_NEW_FOOD_DAY_MEAL";
export const HANDLE_INGREDIENT_MULTIPLIER = "HANDLE_INGREDIENT_MULTIPLIER_";
export const HANDLE_MEAL_INPUTS_CHANGE = "HANDLE_MEAL_INPUTS_CHANGE";
