export const FETCH_USER_INGREDIENTS_START = "FETCH_USER_INGREDIENTS_START";
export const FETCH_USER_INGREDIENTS_SUCCESS = "FETCH_USER_INGREDIENTS_SUCCESS";
export const FETCH_USER_INGREDIENTS_ERROR = "FETCH_USER_INGREDIENTS_ERROR";

export const FETCH_INGREDIENT_TYPES_START = "FETCH_INGREDIENT_TYPES_START";
export const FETCH_INGREDIENT_TYPES_SUCCESS = "FETCH_INGREDIENT_TYPES_SUCCESS";
export const FETCH_INGREDIENT_TYPES_ERROR = "FETCH_INGREDIENT_TYPES_ERROR";

export const CREATE_USER_INGREDIENT_START = "CREATE_USER_INGREDIENT_START";
export const CREATE_USER_INGREDIENT_SUCCESS = "CREATE_USER_INGREDIENT_SUCCESS";
export const CREATE_USER_INGREDIENT_ERROR = "CREATE_USER_INGREDIENT_ERROR";

export const DELETE_USER_INGREDIENT_START = "DELETE_USER_INGREDIENT_START";
export const DELETE_USER_INGREDIENT_SUCCESS = "DELETE_USER_INGREDIENT_SUCCESS";
export const DELETE_USER_INGREDIENT_ERROR = "DELETE_USER_INGREDIENT_ERROR";

export const UPDATE_USER_INGREDIENT_START = "UPDATE_USER_INGREDIENT_START";
export const UPDATE_USER_INGREDIENT_SUCCESS = "UPDATE_USER_INGREDIENT_SUCCESS";
export const UPDATE_USER_INGREDIENT_ERROR = "UPDATE_USER_INGREDIENT_ERROR";

export const FETCH_USER_INGREDIENTS_BY_NAME_START =
  "FETCH_USER_INGREDIENTS_BY_NAME_START";
export const FETCH_USER_INGREDIENTS_BY_NAME_SUCCESS =
  "FETCH_USER_INGREDIENTS_BY_NAME_SUCCESS";
export const FETCH_USER_INGREDIENTS_BY_NAME_ERROR =
  "FETCH_USER_INGREDIENTS_BY_NAME_ERROR";
